version: '3.4'

services:
  catalogdb:
    image: mongo

  shopcartdb:
    image: redis  

  orderdb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
        context: .
        dockerfile: src/Catalog.API/Dockerfile

  shopcart.api:
    image: ${DOCKER_REGISTRY-}shopcartapi
    build:
      context: .
      dockerfile: src/ShopCart.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering.API/Ordering.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/APIGateway/Dockerfile

  aspnetrunbasics:
    image: ${DOCKER_REGISTRY-}aspnetrunbasics
    build:
      context: .
      dockerfile: src/WebApp/AspnetRunBasics/Dockerfile